DARK = {
    "bg":           "#0d0f18",
    "sidebar":      "#13151f",
    "card":         "#1a1d2e",
    "card2":        "#21243a",
    "border":       "#2a2d45",
    "accent":       "#7c6af7",
    "accent2":      "#5eead4",
    "text":         "#e8eaf6",
    "subtext":      "#7b7f9e",
    "input_bg":     "#12141e",
    "btn":          "#7c6af7",
    "btn_hover":    "#6c5ae7",
    "btn_text":     "#ffffff",
    "success":      "#4ade80",
    "warning":      "#facc15",
    "error":        "#f87171",
    "highlight":    "#2d2f4a",
}

LIGHT = {
    "bg":           "#f0f2ff",
    "sidebar":      "#e4e7ff",
    "card":         "#ffffff",
    "card2":        "#f5f6ff",
    "border":       "#d0d3f0",
    "accent":       "#6c5ae7",
    "accent2":      "#0d9488",
    "text":         "#1a1b2e",
    "subtext":      "#6b6f8e",
    "input_bg":     "#f8f9ff",
    "btn":          "#6c5ae7",
    "btn_hover":    "#5b4ad6",
    "btn_text":     "#ffffff",
    "success":      "#16a34a",
    "warning":      "#ca8a04",
    "error":        "#dc2626",
    "highlight":    "#ececff",
}

TRANSLATIONS = {
    "fr": {
        "app_title":      "Boite à Outils",
        "qr":             "QR Code",
        "translator":     "Traducteur",
        "weather":        "Météo",
        "converter":      "Convertisseur",
        "file_conv":      "Convertisseur Fichiers",
        "calculator":     "Calculatrice",
        "clock":          "Horloge & Timer",
        "theme_dark":     "Sombre",
        "theme_light":    "Clair",
        "lang_btn":       "EN",
        "generate":       "Générer",
        "translate":      "Traduire",
        "search":         "Rechercher",
        "convert":        "Convertir",
        "calculate":      "Calculer",
        "copy":           "Copier",
        "save":           "Enregistrer",
        "clear":          "Effacer",
        "from_lang":      "De",
        "to_lang":        "Vers",
        "text_to_trans":  "Texte à traduire...",
        "result":         "Résultat",
        "city":           "Ville...",
        "from_unit":      "De",
        "to_unit":        "Vers",
        "value":          "Valeur",
        "category":       "Catégorie",
        "input_file":     "Fichier source",
        "output_fmt":     "Format cible",
        "browse":         "Parcourir",
        "start":          "Démarrer",
        "stop":           "Stop",
        "reset":          "Réinitialiser",
        "lap":            "Tour",
        "set_timer":      "Durée (mm:ss)",
        "world_clock":    "Horloge Mondiale",
        "add_city":       "Ajouter une ville",
        "password":       "Mot de passe",
        "length":         "Longueur",
        "copied":         "Copié !",
        "error":          "Erreur",
        "qr_input":       "Texte ou URL...",
        "basic_calc":     "Basique",
        "advanced_calc":  "Avancée",
        "history":        "Historique",
        "password":       "Mots de passe",
        "encoder":        "Encodeur / Décodeur",
        "colors":         "Couleurs",
        "metadata":       "Métadonnées",
        "media":          "Lecteur Média",
        "youtube":        "YouTube Downloader",
    },
    "en": {
        "app_title":      "Toolbox",
        "qr":             "QR Code",
        "translator":     "Translator",
        "weather":        "Weather",
        "converter":      "Converter",
        "file_conv":      "File Converter",
        "calculator":     "Calculator",
        "clock":          "Clock & Timer",
        "theme_dark":     "Dark",
        "theme_light":    "Light",
        "lang_btn":       "FR",
        "generate":       "Generate",
        "translate":      "Translate",
        "search":         "Search",
        "convert":        "Convert",
        "calculate":      "Calculate",
        "copy":           "Copy",
        "save":           "Save",
        "clear":          "Clear",
        "from_lang":      "From",
        "to_lang":        "To",
        "text_to_trans":  "Text to translate...",
        "result":         "Result",
        "city":           "City...",
        "from_unit":      "From",
        "to_unit":        "To",
        "value":          "Value",
        "category":       "Category",
        "input_file":     "Source file",
        "output_fmt":     "Target format",
        "browse":         "Browse",
        "start":          "Start",
        "stop":           "Stop",
        "reset":          "Reset",
        "lap":            "Lap",
        "set_timer":      "Duration (mm:ss)",
        "world_clock":    "World Clock",
        "add_city":       "Add a city",
        "password":       "Password",
        "length":         "Length",
        "copied":         "Copied!",
        "error":          "Error",
        "qr_input":       "Text or URL...",
        "basic_calc":     "Basic",
        "advanced_calc":  "Advanced",
        "history":        "History",
        "password":       "Passwords",
        "encoder":        "Encoder / Decoder",
        "colors":         "Colors",
        "metadata":       "Metadata",
        "media":          "Media Player",
        "youtube":        "YouTube Downloader",
    }
}